### ISSUE TITLE
do not fail when file is read-only

### ISSUE THREAD

**Issue by tex** [dyng/ctrlsf.vim#101]
Hi, that's me again :-)

I'm forced to use ClearCase which makes all files read-only.
When running ctrlsf over those files it fails to write changes.

Is it possible to register some function / callback into ctrlsf so I could checkout (this makes file read-write) before ctrlsf writes into it?

Or just simple overwrite with question (Aynq) sould suffice too.

Thanks!

**Comment by dyng** [comment]
Hi,

I'm sorry about that not familiar with ClearCase, is the read-only restriction applied in file-system level? If so, I'm afraid vim can't pass through it easily. ctrlsf is using vim's `writefile()` function to write content back to its original file, you can try to use the same function, fix it, write to read-only file in your case. let me know if you succeed.

> Is it possible to register some function / callback into ctrlsf so I could checkout (this makes file read-write) before ctrlsf writes into it?

At the current time there is no such a trigger / callback, but if it turns out to be necessary, I'll introduce one.

**Comment by dyng** [comment]
Due to the lack of further information, I'll close this issue. But feel free to reopen it if you have new informations.
