### ISSUE TITLE
Better definition of project root

### ISSUE THREAD

**Issue by lervag** [dyng/ctrlsf.vim#112]
I've begun to use the `project` setting for default root. However, this seems to work bad whenever there is no project. I found the responsible code:

```vim
        let path = {
            \ 'project' : ctrlsf#fs#FindVcsRoot(),
            \ 'cwd'     : getcwd(),
            \ }[g:ctrlsf_default_root]
        " If project root is not found, use current file
        if empty(path)
            let path = expand('%:p')
        endif
```

Here it seems that if the `FindVcsRoot` does not return anything, then `ctrlsf` only searches within the current file. I would suggest to instead use `getcwd` as a fallback, so that it searches the current working directory.

The rationale is that I _don't_ use `ctrlsf` for searching the current file. I use it to search multiple files. If I want to search the current file, I instead use normal search (e.g. `/`, `*`, ...).

**Comment by dyng** [comment]
related to #111.

**Comment by lervag** [comment]
Yes, I think there are some interesting thoughts in #111. Personally, I think that a project root combined with a reasonable fallback will be good enough.

**Comment by dyng** [comment]
I have implemented a new option `project+cwd` for `g:ctrlsf_default_root`, which may solve your trouble. Please checkout `feature/new-option-for-default-root` branch and have a try.

I recalled that why I made current file as a fallback when project root can't be found. Because I thought *cwd* is not a obvious fallback of project root and current file is the **safest** one. Sometimes I will open a file in MacVim (while *cwd* is my home directory), if CtrlSF is using *cwd* as a fallback, an absence of project root will cause a full search of home directory and it needs some seconds to stop.

I think it's not easy to cover all situations. Let me know if you have any better idea. Thanks.

**Comment by lervag** [comment]
This works well for me. Thanks!

**Comment by dyng** [comment]
Hi, I have implemented two sub-options for `g:ctrlsf_default_root` and removed `project+cwd` in the latest commit of `feature/new-option-for-default-root`, please update your local branch. I'm sorry for this breaking change.

The new value is 'let g:ctrlsf_default_root = project+fw', please update your *vimrc* and have a try.

**Comment by lervag** [comment]
No problem, this seems like a good change.

**Comment by dyng** [comment]
Feature branch has been merged into `master`. Thanks for your issue report. :)

**Comment by lervag** [comment]
Thank you for solving it in a good way and for creating a wonderful plugin!
