### ISSUE TITLE
Question:  How can I open normal ctrlsf window from quickfix results?

### ISSUE THREAD

**Issue by synic** [dyng/ctrlsf.vim#154]
I would like to use `:CtrlSFQuickfix` by default, but also provide a keybinding that will execute the same search terms in the regular ctrlsf window.  

Usecase is, I want to perform a search, but then be able to edit the search results if I want later.  Is there a way to do this now?  Are the search terms stored somewhere globally?

**Comment by dyng** [comment]
For your question, the search term is stored in plugin scope, I'm sorry that there is no global accessible one now.

But I'm curious about **why you favor `:CtrlSFQuickfix` over `:CtrlSF`?** I have added *quickfix*-serial commands because of a user [request](https://github.com/dyng/ctrlsf.vim/pull/92), but not so satisfied with it myself. Mostly because of its limited feature, inconsistent interface and I almost *never* have used it.

I think it's time for me to know why users need `:CtrlSFQuickfix`, maybe I can provide a more useful alternative.

**Comment by synic** [comment]
Sometimes I don't care about context as much as I care about just finding a file that contains a term, and if there a lot of files, the CtrlSF window becomes less useful as it becomes longer and longer

**Comment by dyng** [comment]
If there is a command that you can switch result window between 'compact' view and 'normal' view, does that suffice your needs?

**Comment by synic** [comment]
Absolutely!

**Comment by dyng** [comment]
Close this issue as #159 is merged.
