### ISSUE TITLE
set shellslash cause Ctrlsf/Ripgrep to fail

### ISSUE THREAD

**Issue by harg** [dyng/ctrlsf.vim#164]
## Issue

Enabling "shellslash" (`set shellslash` on .vimrc) on Microsoft Windows Gvim cause Ctrlsf/Ripgrep to fail.
The command sent to the shell is using simple quotes around parameters instead of double quotes.

|  field  |                value                 |
|:-------:|:------------------------------------:|
|   os    |       *Microsoft Windows 10*        |
|   vim   | *Gvim latest version* |
| backend |             *rg 0.5.0*              |
| locale  |            *en_US.UTF-8*             |

Current command :
`rg -C 3 --fixed-strings --color never --line-number 'mysearch' 'C:/my/folder' `

Shoud be :
`rg -C 3 --fixed-strings --color never --line-number "mysearch" "C:/my/folder" `

**Comment by dyng** [comment]
I'm sorry that I have no window device to reproduce your issue, so I think you should debug it yourself.

ctrlsf builds its command in the below function:

https://github.com/dyng/ctrlsf.vim/blob/master/autoload/ctrlsf/backend.vim#L69-L157

**Comment by michaelmalick** [comment]
I also encounter this issue on Windows 10 with the `set shellslash` option.
@harg correctly points out the problem, CtrlSF puts single quotes around the
search text and directory, when they should be double quotes on Windows. I think
the issue comes from the use of `shellescape` in the plugins `s:Escape` function
(in the backend.vim script). When `shellslash` is set on Windows, the
`shellescape` function uses single quotes, rather than the required double
quotes (see `:h shellescape`).

One solution to this issue is to replace the `shellescape` function inside
`s:Escape` with a custom function (see below for an example) that handles the
quoting for Windows.


```
function! s:Shellescape(arg)
  if has('win32')
    return '"' . substitute(a:arg, '"', '\"', 'g') . '"'
  else
    return shellescape(a:arg)
  endif
endfunction
```

**Comment by dyng** [comment]
I have submitted a patch on `fix/shellescape-on-windows` branch. Please checkout it and test if it works on windows.

**Comment by michaelmalick** [comment]
Thanks for your quick response! Looks like there is a small typo in the patch where 'utils' was spelled 'utls' on line 209 of the backend.vim file. Interestingly, the patch works in vim with this typo, but not neovim.

https://github.com/dyng/ctrlsf.vim/blob/b8636ef1476beec39c39c8aef2b78c76c5d9f5dc/autoload/ctrlsf/backend.vim#L209

**Comment by dyng** [comment]
@michaelmalick Aha, I have missed the typo because of the 'interesting' behavior of Vim. Merging done. Thank you for your contribution!

**Comment by michaelmalick** [comment]
Great, thank you! Everything seems to be working on Windows 10 for both vim and neovim.
