### ISSUE TITLE
Interactive search

### ISSUE THREAD

**Issue by lervag** [dyng/ctrlsf.vim#211]
I just recently learned of [vim-swoop](https://github.com/pelodelfuego/vim-swoop), which seems very similar to ctrlsf. However, it has one feature that seems useful: interactive search. That is, would it be possible to allow an interactive search that will show and update the results as I type? I think this could be useful.

**Comment by dyng** [comment]
Yes It looks fancy but `vim-swoop` works absolutely different from `ctrlsf` as it searches only in all loaded buffers, so it depends no external searching command (like `ag`, `ack` or something else) and it is **FAST**. Interactive search is not possible for `ctrlsf` because `ctrlsf` does more works than `vim-swoop` and can't be so **FAST**.

**Comment by lervag** [comment]
I see, thanks for the explanation. And thanks for a very useful plugin! :)
