### ISSUE TITLE
Highlight of words ending in ! or ?

### ISSUE THREAD

**Issue by dalizard** [dyng/ctrlsf.vim#25]
Hi there!

First of all, thank you for the great plugin! I was trying to find an answer to this on my own, but I think I need help. In Ruby, a method name can end with `?` or `!` and when you do `:CtrlSF email_confirmed?` it's desirable for the highlighter to be aware of the `?` or `!` characters. However, currently it is not. It only highlights the `email_confirmed` although the search itself includes the question mark. Any ideas or suggestions?

**Comment by dyng** [comment]
Hi, @dalizard .

A quick answer is:

- For `?`, use `:CtrlSF 'email_confirmed\?'`, as `?` is a special character in regular expression.
- For `!`, `:CtrlSF do_something_danger!` will do the job as you expect.

More about implementation details:

The initial design concept of CtrlSF is an interface of ag/ack on shell which passes all arguments literally to ag/ack, so you can imagine you are using ag/ack from vim (just replace `:CtrlSF` with `ag/ack`). That is why `?` should be escaped and the whole search pattern need to be quoted.

But later I found it is not so useful and sometimes counter-intuitive. I'll change it and design a more  comfortable interface in upcoming v1.0, but otherwise it will break backward compatibility.

**Comment by dalizard** [comment]
Thank you for your time and precise explanation! :)
