### ISSUE TITLE
noremap <Plug> commands doesn't work?

### ISSUE THREAD

**Issue by jwkvam** [dyng/ctrlsf.vim#28]
There's probably some simple explanation because I don't understand vim mapping well enough but I was confused as to why I couldn't just do
```nnoremap     <C-F>f <Plug>CtrlSFPrompt```
and expect that to work. I finally did what is said on the readme but found it confusing that I couldn't use the `noremap` versions.

**Comment by dyng** [comment]
If you have read the help doc about `<Plug>`, you will find the reason is simple. **Because `<Plug>` is designed for remap**.

Actually, CtrlSF remap `<Plug>CtrlSFPrompt` like this:

```
nnoremap <Plug>CtrlSFPrompt :CtrlSF<Space>
```

If you define a `nnoremap` rather than `nmap`, you prevent the remap for `<Plug>CtrlSFPrompt` , and leave it as a series of plain key strokes.

Hope my explanation could help.
