### ISSUE TITLE
Problem with saving files in dos fileformat/windows line endings/crlf/gah stuff 

### ISSUE THREAD

**Issue by a666** [dyng/ctrlsf.vim#299]
### Issue description

In a file with windows line terminators (crlf) upon editing it in the CtrlSF window and saving the file, it is skipped because it appears changed (`has been changed since last search. Skip this file.`)

Debug sends: `InconsistentContent: [Lnum]: 1, [FileInMem]: tets^M, [FileOnDisk]: tets`

This happens consistently. 
Once I set the file format with `set ff=unix` and save the file, editing and saving the files via the CtrlSF window works without problem.

Notice that either FileOnDisk is possibly wrong: the `tets` line really does end in `crlf` but vim does not display the famous `^M` when `ff=dos`.
Or that FileInMem should be fileformat aware (should not display `^M`).

### Things about your system and environment

|  field  |                value                 |
|:-------:|:------------------------------------:|
|   os    |       *Arch*        |
|   vim   | *NVIM v0.4.4* |
| backend |             *ripgrep 12.1.1*              |
| locale  |            *en_US.UTF-8*             |

**Comment by Nealium** [comment]
I also ran into this issue, same error: **the buff has ^M and the disk doesn't**,
Fails `VerifyConsistent`  *(edit.vim Line ~150)* it was actually mentioned here https://github.com/dyng/ctrlsf.vim/issues/58 by tex

@a666 might be having the same behavior, my__CTRLSF__ results window is rendering the ^M because it's a Unix file type, but must not be reading them in during the `readfile()` *(edit.vim line ~139)* for the `VerifyConsistent` or `VerifyConsistent` is broken when it comes to ^M

My solution, was to remove all the ^M from the results:
1. Goto `autoload\ctrlsf\class\line.vim`
2. Search for `'content' : a:content,` *(Line ~22)*
3. Replace `a:content` => `substitute(a:content, "\r", "", "")`

The ^M are added back at `ctrlsf#fs#DetectFileFormat(file) == 'dos'` *(edit.vim Line ~167)*

I've done min testing, changing the filefomats + saving, and the solution seems to be working. It doesn't change the fileformat, just the actual edits.

If someone has a more elegant solution, let me know.. this is my first vimscript experience and I was just throwing stuff at the wall

**Comment by JoseConseco** [comment]
I have similar issue when ff -> dos.  Using: set ff=unix  fixes the issue.  Still it would be great to have this fixed in ctrlsf. @dyng any chances for fix?

**Comment by dyng** [comment]
@JoseConseco Sorry for this late reply. https://github.com/dyng/ctrlsf.vim/issues/291#issuecomment-640155655 is exactly reason for your issue. I'm not sure if neovim have fixed it already (I'm using vanilla vim), but if you can find a way to work out, I'm glad to merge your pull request.
