### ISSUE TITLE
Airline statusline funcref function warning.

### ISSUE THREAD

**Issue by zaferot** [dyng/ctrlsf.vim#32]
Hi,

Every time I edit my `.vimrc` and save changes I get the following warning:
`The airline statusline funcref function('CtrlSFStatusLine') has already been added.`

As far as I understand it's not critical, right? But it's quite annoying. How can I fix it?
Thanks!

**Comment by dyng** [comment]
Do you have some auto reloading mechanism for your `.vimrc` file (and plugins) when saving it? A complete `.vimrc` may be helpful for my debugging.

Either way, I think the reason for this issue is that I forgot to add loading-guard snippet at the beginning of `after/plugin/ctrlsf.vim`. I will fix it soon. Thank you for bug report!

**Comment by dyng** [comment]
Fixed in 395a0d4.

Please have a try with latest version. If the issue remains, feel free to report here.

**Comment by zaferot** [comment]
It's working now! Thanks!
